-- Frontend Chat production schema for Supabase.
-- Run this in Supabase SQL Editor, then enable Realtime for messages and notifications.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 2 and 80),
  username text unique check (username ~ '^[a-z0-9_]{3,30}$'),
  phone_number text unique,
  avatar_url text,
  bio text check (char_length(bio) <= 160),
  notifications_enabled boolean not null default true,
  read_receipts_enabled boolean not null default true,
  theme text not null default 'light' check (theme in ('light', 'dark', 'system')),
  is_online boolean not null default false,
  last_seen timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  title text,
  is_group boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.conversation_participants (
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (conversation_id, user_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 4000),
  reply_to_id bigint references public.messages(id) on delete set null,
  attachment_url text,
  attachment_type text,
  created_at timestamptz not null default now()
);

create table if not exists public.message_receipts (
  message_id bigint not null references public.messages(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  delivered_at timestamptz,
  read_at timestamptz,
  primary key (message_id, user_id)
);

create table if not exists public.message_reactions (
  message_id bigint not null references public.messages(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  emoji text not null check (char_length(emoji) between 1 and 16),
  created_at timestamptz not null default now(),
  primary key (message_id, user_id)
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  actor_id uuid not null references public.profiles(id) on delete cascade,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  message_id bigint not null references public.messages(id) on delete cascade,
  body text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, name) values (new.id, coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_participants enable row level security;
alter table public.messages enable row level security;
alter table public.message_receipts enable row level security;
alter table public.message_reactions enable row level security;
alter table public.notifications enable row level security;

create or replace function public.is_conversation_member(target_conversation bigint)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.conversation_participants where conversation_id = target_conversation and user_id = auth.uid());
$$;

create policy "profiles are searchable by authenticated users" on public.profiles for select to authenticated using (true);
create policy "users update their own profile" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
create policy "members can view conversations" on public.conversations for select to authenticated using (public.is_conversation_member(id));
create policy "authenticated users create conversations" on public.conversations for insert to authenticated with check (true);
create policy "members can view participants" on public.conversation_participants for select to authenticated using (public.is_conversation_member(conversation_id));
create policy "conversation creators add participants" on public.conversation_participants for insert to authenticated with check (user_id = auth.uid() or public.is_conversation_member(conversation_id));
create policy "members can read messages" on public.messages for select to authenticated using (public.is_conversation_member(conversation_id));
create policy "members can send messages" on public.messages for insert to authenticated with check (sender_id = auth.uid() and public.is_conversation_member(conversation_id));
create policy "members can read receipts" on public.message_receipts for select to authenticated using (user_id = auth.uid() or exists (select 1 from public.messages m where m.id = message_id and m.sender_id = auth.uid()));
create policy "users update their receipts" on public.message_receipts for insert to authenticated with check (user_id = auth.uid());
create policy "members can read reactions" on public.message_reactions for select to authenticated using (exists (select 1 from public.messages m where m.id = message_id and public.is_conversation_member(m.conversation_id)));
create policy "users manage their reactions" on public.message_reactions for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "users read their notifications" on public.notifications for select to authenticated using (user_id = auth.uid());
create policy "users mark notifications read" on public.notifications for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

alter publication supabase_realtime add table public.messages;
alter publication supabase_realtime add table public.notifications;
alter publication supabase_realtime add table public.profiles;
