const API = window.location.port === '8000' ? '' : 'http://127.0.0.1:8000';
const state = { token: localStorage.getItem('frontend-chat-token'), user: null, conversations: [], selectedId: null, socket: null, authMode: 'login', notifications: [], unreadNotifications: 0 };
const $ = (selector) => document.querySelector(selector);
const initials = (name = 'User') => name.split(' ').map(part => part[0]).join('').slice(0, 2).toUpperCase();
const formatTime = (value) => new Date(value).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' });
const escapeHtml = (value) => String(value).replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[char]));

async function request(path, options = {}) {
  const response = await fetch(`${API}${path}`, { headers: { 'Content-Type': 'application/json', ...(state.token ? { Authorization: `Bearer ${state.token}` } : {}), ...(options.headers || {}) }, ...options });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.detail || 'Something went wrong');
  return data;
}
function showToast(message) { const toast = $('#toast'); toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2600); }
function setAuthMode(mode) { state.authMode = mode; document.querySelectorAll('.tab').forEach(tab => tab.classList.toggle('active', tab.dataset.authMode === mode)); $('#name-field').classList.toggle('hidden', mode !== 'register'); $('#auth-submit-label').textContent = mode === 'register' ? 'Create my account' : 'Enter Frontend Chat'; $('#auth-error').textContent = ''; }
async function submitAuth(event) { event.preventDefault(); const payload = { email: $('#email').value, password: $('#password').value }; if (state.authMode === 'register') payload.name = $('#name').value; $('#auth-error').textContent = ''; try { const data = await request(`/auth/${state.authMode}`, { method: 'POST', body: JSON.stringify(payload) }); state.token = data.token; state.user = data.user; localStorage.setItem('frontend-chat-token', state.token); await enterChat(); } catch (error) { $('#auth-error').textContent = error.message; } }
function renderProfile() { $('#profile-name').textContent = state.user.name; $('#profile-email').textContent = state.user.email; $('#profile-avatar').textContent = initials(state.user.name); }
function renderConversations(filter = '') { const list = $('#conversation-list'); const query = filter.toLowerCase(); const rows = state.conversations.filter(row => `${row.title || ''} ${row.last_message || ''}`.toLowerCase().includes(query)); list.innerHTML = rows.length ? rows.map(row => `<button class="conversation-item ${row.id === state.selectedId ? 'active' : ''}" data-conversation-id="${row.id}"><strong>${escapeHtml(row.title || `Conversation ${row.id}`)}</strong><span>${escapeHtml(row.last_message || 'No messages yet')}</span></button>`).join('') : '<p class="muted" style="padding:12px">No conversations yet.</p>'; list.querySelectorAll('[data-conversation-id]').forEach(button => button.addEventListener('click', () => selectConversation(Number(button.dataset.conversationId)))); }
async function loadConversations() { state.conversations = await request('/conversations'); renderConversations($('#conversation-search').value); }
async function loadNotifications() { const data = await request('/notifications'); state.notifications = data.items; state.unreadNotifications = data.unread_count; renderNotifications(); }
function renderNotifications() { const count = $('#notification-count'); count.textContent = state.unreadNotifications > 9 ? '9+' : state.unreadNotifications; count.classList.toggle('hidden', state.unreadNotifications === 0); const list = $('#notification-list'); list.innerHTML = state.notifications.length ? state.notifications.map(item => `<button class="notification-item ${item.is_read ? '' : 'unread'}" data-notification-conversation="${item.conversation_id}"><strong>${escapeHtml(item.actor_name)} sent a message</strong><span>${escapeHtml(item.body)} · ${formatTime(item.created_at)}</span></button>`).join('') : '<p class="muted">You are all caught up.</p>'; list.querySelectorAll('[data-notification-conversation]').forEach(button => button.addEventListener('click', () => { $('#notifications-panel').classList.add('hidden'); selectConversation(Number(button.dataset.notificationConversation)); })); }
async function markNotificationsRead() { await request('/notifications/read-all', { method: 'POST' }); state.notifications = state.notifications.map(item => ({ ...item, is_read: true })); state.unreadNotifications = 0; renderNotifications(); }
async function selectConversation(id) { state.selectedId = id; const conversation = state.conversations.find(row => row.id === id); $('#conversation-title').textContent = conversation?.title || `Conversation ${id}`; $('#conversation-meta').textContent = `${conversation?.participant_ids?.length || 1} participant${conversation?.participant_ids?.length === 1 ? '' : 's'}`; $('#message-input').disabled = false; $('#send-button').disabled = false; renderConversations($('#conversation-search').value); const messages = await request(`/conversations/${id}/messages`); renderMessages(messages); }
function renderMessages(messages) { const list = $('#message-list'); list.innerHTML = messages.length ? messages.map(message => `<article class="message ${message.sender_id === state.user.id ? 'mine' : ''}" data-message-id="${message.id}"><div class="avatar">${initials(message.sender_name)}</div><div class="message-content"><div class="message-meta">${escapeHtml(message.sender_name)} · ${formatTime(message.created_at)}</div><div class="bubble">${escapeHtml(message.body)}</div></div></article>`).join('') : '<div class="empty-state"><div class="empty-icon">&#10132;</div><h3>No messages yet</h3><p>Start the conversation below.</p></div>'; list.scrollTop = list.scrollHeight; }
async function sendMessage(event) { event.preventDefault(); const input = $('#message-input'); const body = input.value.trim(); if (!body || !state.selectedId) return; input.value = ''; try { const message = await request(`/conversations/${state.selectedId}/messages`, { method: 'POST', body: JSON.stringify({ body }) }); appendMessage(message); await loadConversations(); } catch (error) { showToast(error.message); input.value = body; } }
function appendMessage(message) { if (message.conversation_id !== state.selectedId || document.querySelector(`[data-message-id="${message.id}"]`)) return; const list = $('#message-list'); if (list.querySelector('.empty-state')) list.innerHTML = ''; list.insertAdjacentHTML('beforeend', `<article class="message ${message.sender_id === state.user.id ? 'mine' : ''}" data-message-id="${message.id}"><div class="avatar">${initials(message.sender_name)}</div><div class="message-content"><div class="message-meta">${escapeHtml(message.sender_name)} · ${formatTime(message.created_at)}</div><div class="bubble">${escapeHtml(message.body)}</div></div></article>`); list.scrollTop = list.scrollHeight; }
async function searchUsers() { const query = $('#user-search').value.trim(); if (!query) { $('#user-results').innerHTML = ''; return; } const users = await request(`/users?q=${encodeURIComponent(query)}`); $('#user-results').innerHTML = users.length ? users.map(user => `<button class="user-result" data-user-id="${user.id}"><div class="avatar">${initials(user.name)}</div><div><strong>${escapeHtml(user.name)}</strong><span>${escapeHtml(user.email)}</span></div></button>`).join('') : '<p class="muted">No people found.</p>'; $('#user-results').querySelectorAll('[data-user-id]').forEach(button => button.addEventListener('click', () => createConversation(Number(button.dataset.userId)))); }
async function createConversation(participantId) { try { const conversation = await request('/conversations', { method: 'POST', body: JSON.stringify({ participant_ids: [participantId] }) }); $('#new-chat-panel').classList.add('hidden'); $('#user-search').value = ''; await loadConversations(); await selectConversation(conversation.id); } catch (error) { showToast(error.message); } }
function connectSocket() { if (state.socket) state.socket.close(); const socketUrl = `${API.replace('http', 'ws')}/ws?token=${encodeURIComponent(state.token)}`; state.socket = new WebSocket(socketUrl); state.socket.onmessage = event => { const data = JSON.parse(event.data); if (data.type === 'message.created') appendMessage(data.message); if (data.type === 'notification.created') { state.notifications.unshift({ id: `live-${Date.now()}`, ...data.notification }); state.unreadNotifications += 1; renderNotifications(); showToast(`${data.notification.actor_name} sent a new message`); } }; state.socket.onclose = () => setTimeout(() => state.token && connectSocket(), 2500); }
async function enterChat() { $('#auth-view').classList.add('hidden'); $('#chat-view').classList.remove('hidden'); renderProfile(); await Promise.all([loadConversations(), loadNotifications()]); connectSocket(); }
function logout() { localStorage.removeItem('frontend-chat-token'); state.token = null; state.user = null; state.socket?.close(); $('#chat-view').classList.add('hidden'); $('#auth-view').classList.remove('hidden'); }
async function boot() { document.querySelectorAll('[data-auth-mode]').forEach(tab => tab.addEventListener('click', () => setAuthMode(tab.dataset.authMode))); $('#auth-form').addEventListener('submit', submitAuth); $('#message-form').addEventListener('submit', sendMessage); $('#logout').addEventListener('click', logout); $('#conversation-search').addEventListener('input', event => renderConversations(event.target.value)); $('#new-chat').addEventListener('click', () => $('#new-chat-panel').classList.remove('hidden')); $('#close-new-chat').addEventListener('click', () => $('#new-chat-panel').classList.add('hidden')); $('#notifications-button').addEventListener('click', async () => { $('#notifications-panel').classList.toggle('hidden'); if (!$('#notifications-panel').classList.contains('hidden')) await loadNotifications(); }); $('#close-notifications').addEventListener('click', () => $('#notifications-panel').classList.add('hidden')); $('#mark-notifications-read').addEventListener('click', markNotificationsRead); let searchTimer; $('#user-search').addEventListener('input', () => { clearTimeout(searchTimer); searchTimer = setTimeout(searchUsers, 250); }); if (state.token) { try { const data = await request('/me'); state.user = data.user; await enterChat(); } catch { logout(); } } }
boot();
